export const VOUCHER_LIST_REQUEST = 'VOUCHER_LIST_REQUEST';
export const VOUCHER_LIST_SUCCESS = 'VOUCHER_LIST_SUCCESS';
export const VOUCHER_LIST_FAIL = 'VOUCHER_LIST_FAIL';

export const VOUCHER_DETAILS_REQUEST = 'VOUCHER_DETAILS_REQUEST';
export const VOUCHER_DETAILS_SUCCESS = 'VOUCHER_DETAILS_SUCCESS';
export const VOUCHER_DETAILS_FAIL = 'VOUCHER_DETAILS_FAIL';